[tool.poetry]
name = "uku-audio-processing-course"
version = "0.1.0"
description = ""
authors = ["VSydorskyy <vladimirsydorskyy@gmail.com>", "AntonBazdyrev", ]
readme = "README.md"
packages = [{include = "uku_audio_processing_course"}]

[tool.poetry.dependencies]
python = "^3.10"
jupyterlab = "^4.0.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
